hwi_oauth:
    firewall_names: ['main']
    resource_owners:
        facebook:
            type: 'facebook'
            client_id: '%env(HWI_OAUTH_FACEBOOK_APP_ID)%'
            client_secret: '%env(HWI_OAUTH_FACEBOOK_APP_SECRET)%'
            scope: 'email'
