app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /admin

glyynn_admin:
    resource: "@GlyynnAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /

disjfa_mozaic:
    resource: "@DisjfaMozaicBundle/Controller/"
    type:     annotation
    prefix:   /
