services:
    user.service.oauth_user_provider:
        class: UserBundle\Services\OAuthUserProvider
        arguments:
          - '@fos_user.user_manager.default'
          - {facebook: 'facebook_id'}

    user.user_menu_listener:
        class: UserBundle\GlynnAdminMenu\UserMenuListener
        arguments:
          - '@doctrine.orm.entity_manager'
          - '@security.token_storage'
        tags:
          - { name: 'kernel.event_listener', event: 'glynn_admin.menu_configure', method: 'onMenuConfigure', priority: -50 }