services:
    user.service.oauth_user_provider:
        class: UserBundle\Services\OAuthUserProvider
        arguments:
          - '@fos_user.user_manager.default'
          - {facebook: 'facebook_id'}

